collection_name: agent_dd
persist_directory: cbroma_db
k : 5 
data_path: data
md5_hex_store: md5.txt

allow_knowledge_file_type: ["txt", "pdf"] 

chunk_size: 200
chunk_overlap: 20
separator : ['\n', '。', '？', '！', '；', '、', '，', '：', '（', '）', '《', '》', '「', '」', '『', '』', '【', '】', '〔', '〕', '〈', '〉', '《》', '〈〉', '【】', '〔〕', '（）', '{}[]', '【】', '（）', '【】', '（）', '【】', '（）',]